config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-us', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails')}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
  end

  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.by_position
  end

  def angular
    @angular_portfolio_item = Portfolio.angular
  end

  def new
    @portfolio_items = Portfolio.new
    3.times { @portfolio_items.technologies.build }
  end

  def show
  end

  def create
    @portfolio_items = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_items.save
        format.html {redirect_to portfolios_path, notice: 'Portfolio Item Generated.'}
      else
        format.html {render :new}
      end
    end
  end

  def edit
  end

  def update

    respond_to do |format|
      if @portfolio_items.update(portfolio_params)
        format.html {redirect_to portfolios_path, notice: 'Portfolio Item Update.'}
      else
        format.html {render :edit}
      end
    end
  end

  def destroy
    @portfolio_items.destroy
    respond_to do |format|
      format.html{redirect_to portfolios_url, notice: "Portfolio was removed."}
    end
  end


  private
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body, 
                                      technologies_attributes: [:name]
                                      )
  end

  def set_portfolio
    @portfolio_items = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_items) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
   <hr>
    <h3>Technologies Used:</h3>
    <div class="form-group">
      <%= form.fields_for :technologies do |technology_form| %>
      <div class="form-group">
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name, class: 'form-control' %>
      </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.submit "Submit", class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card mb-4 box-shadow">
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <div class="card-body">
    <p <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %></p>
  </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin)%>

<% @angular_portfolio_item.each do |portfolio_items| %>
  <p><%= link_to portfolio_items.title, portfolio_show_path(portfolio_items.id) %></p>
  <p><%= portfolio_items.subtitle %></p>
  <p><%= portfolio_items.body %></p>
  <%= image_tag portfolio_items.thumb_image unless portfolio_items.thumb_image.nil? %>
  <br>
  <%= link_to "Edit", edit_portfolio_path(portfolio_items.id) %>
  <%= link_to 'Delete', portfolio_path(portfolio_items.id), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
  <hr>

<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">  
  <h1>Edit This Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row sortable">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a New Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-7'>
      <%= image_tag @portfolio_items.main_image %>
    </div>
    <div class='col-md-5'>
      <h1><%= @portfolio_items.title %></h1>
      <hr>
      <em><%= @portfolio_items.subtitle %></em>
      <hr>
      <p><%= @portfolio_items.body%></p>


      <h3>Technologies Used</h3>

      <% @portfolio_items.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
    </div>
  </div>
</div>